-- H2 本地文件数据库初始化脚本。骨架表 + 航天器热真空试验与遥测判读业务表。
CREATE TABLE IF NOT EXISTS t_evops_schema_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_no VARCHAR(32) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_evops_schema_version UNIQUE (version_no)
);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('base-0', 'EVOPS 初始工作区');

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('tvac-1', '航天器热真空试验与遥测判读基础闭环');

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('tvac-2', '多租户运营检索与遥测分区聚合');

-- 租户（运营单位，如总体厂所/试验中心）
CREATE TABLE IF NOT EXISTS t_tvac_tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code VARCHAR(64) NOT NULL,
    tenant_name VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_tenant_code UNIQUE (tenant_code)
);

-- 租户账号：role = TENANT_ADMIN（本租户全部数据）/ TENANT_VIEWER（仅授权对象）
CREATE TABLE IF NOT EXISTS t_tvac_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password VARCHAR(128) NOT NULL,
    real_name VARCHAR(64),
    tenant_id BIGINT NOT NULL,
    role VARCHAR(24) NOT NULL DEFAULT 'TENANT_VIEWER',
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_user_username UNIQUE (username),
    CONSTRAINT fk_tvac_user_tenant FOREIGN KEY (tenant_id) REFERENCES t_tvac_tenant(id)
);

-- 对象级授权表与运营检索索引在全部业务表之后创建（见文件末尾，存在外键依赖顺序）

-- 试验件（受试航天器产品/设备）
CREATE TABLE IF NOT EXISTS t_tvac_article (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_code VARCHAR(64) NOT NULL,
    article_name VARCHAR(128) NOT NULL,
    target_model VARCHAR(64),
    batch_no VARCHAR(64) NOT NULL,
    tenant_id BIGINT,
    status VARCHAR(16) NOT NULL DEFAULT 'REGISTERED',
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_article_code UNIQUE (article_code),
    CONSTRAINT uk_tvac_article_batch_name UNIQUE (batch_no, article_name)
);
-- 既有文件库平滑升级（H2 支持 ADD COLUMN IF NOT EXISTS）
ALTER TABLE t_tvac_article ADD COLUMN IF NOT EXISTS tenant_id BIGINT;

-- 试验计划
CREATE TABLE IF NOT EXISTS t_tvac_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_code VARCHAR(64) NOT NULL,
    plan_name VARCHAR(128) NOT NULL,
    article_id BIGINT NOT NULL,
    high_temp_c DECIMAL(8,2) NOT NULL,
    low_temp_c DECIMAL(8,2) NOT NULL,
    vacuum_pa DECIMAL(16,4),
    target_cycles INT NOT NULL DEFAULT 0,
    plan_start_time TIMESTAMP,
    plan_end_time TIMESTAMP,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_plan_code UNIQUE (plan_code),
    CONSTRAINT fk_tvac_plan_article FOREIGN KEY (article_id) REFERENCES t_tvac_article(id)
);

-- 遥测通道
CREATE TABLE IF NOT EXISTS t_tvac_channel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_code VARCHAR(64) NOT NULL,
    channel_name VARCHAR(128) NOT NULL,
    article_id BIGINT NOT NULL,
    measure_type VARCHAR(16) NOT NULL,
    unit VARCHAR(16),
    upper_limit DECIMAL(16,4),
    lower_limit DECIMAL(16,4),
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLED',
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_channel_code UNIQUE (channel_code),
    CONSTRAINT fk_tvac_channel_article FOREIGN KEY (article_id) REFERENCES t_tvac_article(id)
);

-- 试验件温压曲线点（同一计划下按相对秒序记录）
CREATE TABLE IF NOT EXISTS t_tvac_curve_point (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL,
    article_id BIGINT NOT NULL,
    cycle_no INT NOT NULL DEFAULT 1,
    point_time TIMESTAMP NOT NULL,
    offset_sec INT NOT NULL DEFAULT 0,
    temperature_c DECIMAL(8,2) NOT NULL,
    pressure_pa DECIMAL(16,4),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT fk_tvac_curve_plan FOREIGN KEY (plan_id) REFERENCES t_tvac_plan(id),
    CONSTRAINT fk_tvac_curve_article FOREIGN KEY (article_id) REFERENCES t_tvac_article(id)
);
CREATE INDEX IF NOT EXISTS idx_tvac_curve_plan ON t_tvac_curve_point (plan_id, offset_sec);

-- 遥测帧
CREATE TABLE IF NOT EXISTS t_tvac_tm_frame (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    frame_seq VARCHAR(64) NOT NULL,
    plan_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    article_id BIGINT NOT NULL,
    cycle_no INT NOT NULL DEFAULT 1,
    frame_time TIMESTAMP NOT NULL,
    raw_value VARCHAR(128),
    eng_value DECIMAL(16,4),
    limit_flag VARCHAR(8) NOT NULL DEFAULT 'NORMAL',
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_frame_seq UNIQUE (frame_seq),
    CONSTRAINT fk_tvac_frame_plan FOREIGN KEY (plan_id) REFERENCES t_tvac_plan(id),
    CONSTRAINT fk_tvac_frame_channel FOREIGN KEY (channel_id) REFERENCES t_tvac_channel(id),
    CONSTRAINT fk_tvac_frame_article FOREIGN KEY (article_id) REFERENCES t_tvac_article(id)
);
CREATE INDEX IF NOT EXISTS idx_tvac_frame_plan ON t_tvac_tm_frame (plan_id, frame_time);

-- 判读报告
CREATE TABLE IF NOT EXISTS t_tvac_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_no VARCHAR(64) NOT NULL,
    plan_id BIGINT NOT NULL,
    conclusion VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    actual_cycles INT NOT NULL DEFAULT 0,
    total_frames INT NOT NULL DEFAULT 0,
    abnormal_frames INT NOT NULL DEFAULT 0,
    high_temp_reached DECIMAL(8,2),
    low_temp_reached DECIMAL(8,2),
    min_pressure_pa DECIMAL(16,4),
    judged_by VARCHAR(64),
    judged_time TIMESTAMP,
    accepted_by VARCHAR(64),
    accepted_time TIMESTAMP,
    posted_time TIMESTAMP,
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_report_no UNIQUE (report_no),
    CONSTRAINT uk_tvac_report_plan UNIQUE (plan_id),
    CONSTRAINT fk_tvac_report_plan FOREIGN KEY (plan_id) REFERENCES t_tvac_plan(id)
);

-- ============ tvac-2：多租户授权表（外键依赖业务表，置于最后） ============
CREATE TABLE IF NOT EXISTS t_tvac_user_grant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    object_type VARCHAR(16) NOT NULL DEFAULT 'ARTICLE',
    article_id BIGINT NOT NULL,
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_user_grant UNIQUE (user_id, object_type, article_id),
    CONSTRAINT fk_tvac_grant_user FOREIGN KEY (user_id) REFERENCES t_tvac_user(id),
    CONSTRAINT fk_tvac_grant_article FOREIGN KEY (article_id) REFERENCES t_tvac_article(id)
);
CREATE INDEX IF NOT EXISTS idx_tvac_grant_user ON t_tvac_user_grant (user_id, article_id);

-- 运营检索/聚合支撑索引（确定性排序、范围扫描、分区聚合、曲线/帧关联半连接）
CREATE INDEX IF NOT EXISTS idx_tvac_article_time_id ON t_tvac_article (create_time, id);
CREATE INDEX IF NOT EXISTS idx_tvac_article_status_time ON t_tvac_article (status, create_time, id);
CREATE INDEX IF NOT EXISTS idx_tvac_article_batch_time ON t_tvac_article (batch_no, create_time, id);
CREATE INDEX IF NOT EXISTS idx_tvac_plan_time_id ON t_tvac_plan (create_time, id);
CREATE INDEX IF NOT EXISTS idx_tvac_plan_article_time ON t_tvac_plan (article_id, create_time, id);
CREATE INDEX IF NOT EXISTS idx_tvac_plan_status_time ON t_tvac_plan (status, create_time, id);
CREATE INDEX IF NOT EXISTS idx_tvac_plan_start_time ON t_tvac_plan (plan_start_time);
CREATE INDEX IF NOT EXISTS idx_tvac_curve_article_cycle ON t_tvac_curve_point (article_id, cycle_no);
CREATE INDEX IF NOT EXISTS idx_tvac_frame_article_cycle ON t_tvac_tm_frame (article_id, cycle_no);
CREATE INDEX IF NOT EXISTS idx_tvac_frame_article_time ON t_tvac_tm_frame (article_id, frame_time);
CREATE INDEX IF NOT EXISTS idx_tvac_frame_limit ON t_tvac_tm_frame (limit_flag, article_id);
