-- H2 本地文件数据库初始化脚本。骨架表 + 航天器热真空试验与遥测判读业务表。
CREATE TABLE IF NOT EXISTS t_evops_schema_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_no VARCHAR(32) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_evops_schema_version UNIQUE (version_no)
);

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('base-0', 'EVOPS 初始工作区');

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('tvac-1', '航天器热真空试验与遥测判读基础闭环');

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('tvac-2', '多租户运营检索与遥测分区聚合');

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('tvac-3', '观测数据CSV批量导入：分片幂等、逐行隔离与遥测帧重组');

MERGE INTO t_evops_schema_version (version_no, description)
KEY (version_no)
VALUES ('tvac-4', '时序判读规则版本化：峰值/平段/谷值业务区间计算与快照留痕');

-- 租户（运营单位，如总体厂所/试验中心）
CREATE TABLE IF NOT EXISTS t_tvac_tenant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_code VARCHAR(64) NOT NULL,
    tenant_name VARCHAR(128) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_tenant_code UNIQUE (tenant_code)
);

-- 租户账号：role = TENANT_ADMIN（本租户全部数据）/ TENANT_VIEWER（仅授权对象）
CREATE TABLE IF NOT EXISTS t_tvac_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password VARCHAR(128) NOT NULL,
    real_name VARCHAR(64),
    tenant_id BIGINT NOT NULL,
    role VARCHAR(24) NOT NULL DEFAULT 'TENANT_VIEWER',
    status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_user_username UNIQUE (username),
    CONSTRAINT fk_tvac_user_tenant FOREIGN KEY (tenant_id) REFERENCES t_tvac_tenant(id)
);

-- 对象级授权表与运营检索索引在全部业务表之后创建（见文件末尾，存在外键依赖顺序）

-- 试验件（受试航天器产品/设备）
CREATE TABLE IF NOT EXISTS t_tvac_article (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    article_code VARCHAR(64) NOT NULL,
    article_name VARCHAR(128) NOT NULL,
    target_model VARCHAR(64),
    batch_no VARCHAR(64) NOT NULL,
    tenant_id BIGINT,
    status VARCHAR(16) NOT NULL DEFAULT 'REGISTERED',
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_article_code UNIQUE (article_code),
    CONSTRAINT uk_tvac_article_batch_name UNIQUE (batch_no, article_name)
);
-- 既有文件库平滑升级（H2 支持 ADD COLUMN IF NOT EXISTS）
ALTER TABLE t_tvac_article ADD COLUMN IF NOT EXISTS tenant_id BIGINT;

-- 试验计划
CREATE TABLE IF NOT EXISTS t_tvac_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_code VARCHAR(64) NOT NULL,
    plan_name VARCHAR(128) NOT NULL,
    article_id BIGINT NOT NULL,
    high_temp_c DECIMAL(8,2) NOT NULL,
    low_temp_c DECIMAL(8,2) NOT NULL,
    vacuum_pa DECIMAL(16,4),
    target_cycles INT NOT NULL DEFAULT 0,
    plan_start_time TIMESTAMP,
    plan_end_time TIMESTAMP,
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_plan_code UNIQUE (plan_code),
    CONSTRAINT fk_tvac_plan_article FOREIGN KEY (article_id) REFERENCES t_tvac_article(id)
);

-- 遥测通道
CREATE TABLE IF NOT EXISTS t_tvac_channel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_code VARCHAR(64) NOT NULL,
    channel_name VARCHAR(128) NOT NULL,
    article_id BIGINT NOT NULL,
    measure_type VARCHAR(16) NOT NULL,
    unit VARCHAR(16),
    upper_limit DECIMAL(16,4),
    lower_limit DECIMAL(16,4),
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLED',
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_channel_code UNIQUE (channel_code),
    CONSTRAINT fk_tvac_channel_article FOREIGN KEY (article_id) REFERENCES t_tvac_article(id)
);

-- 试验件温压曲线点（同一计划下按相对秒序记录）
CREATE TABLE IF NOT EXISTS t_tvac_curve_point (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL,
    article_id BIGINT NOT NULL,
    cycle_no INT NOT NULL DEFAULT 1,
    point_time TIMESTAMP NOT NULL,
    offset_sec INT NOT NULL DEFAULT 0,
    temperature_c DECIMAL(8,2) NOT NULL,
    pressure_pa DECIMAL(16,4),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT fk_tvac_curve_plan FOREIGN KEY (plan_id) REFERENCES t_tvac_plan(id),
    CONSTRAINT fk_tvac_curve_article FOREIGN KEY (article_id) REFERENCES t_tvac_article(id)
);
CREATE INDEX IF NOT EXISTS idx_tvac_curve_plan ON t_tvac_curve_point (plan_id, offset_sec);

-- 遥测帧
CREATE TABLE IF NOT EXISTS t_tvac_tm_frame (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    frame_seq VARCHAR(64) NOT NULL,
    plan_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    article_id BIGINT NOT NULL,
    cycle_no INT NOT NULL DEFAULT 1,
    frame_time TIMESTAMP NOT NULL,
    raw_value VARCHAR(128),
    eng_value DECIMAL(16,4),
    limit_flag VARCHAR(8) NOT NULL DEFAULT 'NORMAL',
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_frame_seq UNIQUE (frame_seq),
    CONSTRAINT fk_tvac_frame_plan FOREIGN KEY (plan_id) REFERENCES t_tvac_plan(id),
    CONSTRAINT fk_tvac_frame_channel FOREIGN KEY (channel_id) REFERENCES t_tvac_channel(id),
    CONSTRAINT fk_tvac_frame_article FOREIGN KEY (article_id) REFERENCES t_tvac_article(id)
);
CREATE INDEX IF NOT EXISTS idx_tvac_frame_plan ON t_tvac_tm_frame (plan_id, frame_time);

-- 判读报告
CREATE TABLE IF NOT EXISTS t_tvac_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_no VARCHAR(64) NOT NULL,
    plan_id BIGINT NOT NULL,
    conclusion VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    actual_cycles INT NOT NULL DEFAULT 0,
    total_frames INT NOT NULL DEFAULT 0,
    abnormal_frames INT NOT NULL DEFAULT 0,
    high_temp_reached DECIMAL(8,2),
    low_temp_reached DECIMAL(8,2),
    min_pressure_pa DECIMAL(16,4),
    judged_by VARCHAR(64),
    judged_time TIMESTAMP,
    accepted_by VARCHAR(64),
    accepted_time TIMESTAMP,
    posted_time TIMESTAMP,
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_report_no UNIQUE (report_no),
    CONSTRAINT uk_tvac_report_plan UNIQUE (plan_id),
    CONSTRAINT fk_tvac_report_plan FOREIGN KEY (plan_id) REFERENCES t_tvac_plan(id)
);

-- ============ tvac-2：多租户授权表（外键依赖业务表，置于最后） ============
CREATE TABLE IF NOT EXISTS t_tvac_user_grant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    object_type VARCHAR(16) NOT NULL DEFAULT 'ARTICLE',
    article_id BIGINT NOT NULL,
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_user_grant UNIQUE (user_id, object_type, article_id),
    CONSTRAINT fk_tvac_grant_user FOREIGN KEY (user_id) REFERENCES t_tvac_user(id),
    CONSTRAINT fk_tvac_grant_article FOREIGN KEY (article_id) REFERENCES t_tvac_article(id)
);
CREATE INDEX IF NOT EXISTS idx_tvac_grant_user ON t_tvac_user_grant (user_id, article_id);

-- 运营检索/聚合支撑索引（确定性排序、范围扫描、分区聚合、曲线/帧关联半连接）
CREATE INDEX IF NOT EXISTS idx_tvac_article_time_id ON t_tvac_article (create_time, id);
CREATE INDEX IF NOT EXISTS idx_tvac_article_status_time ON t_tvac_article (status, create_time, id);
CREATE INDEX IF NOT EXISTS idx_tvac_article_batch_time ON t_tvac_article (batch_no, create_time, id);
CREATE INDEX IF NOT EXISTS idx_tvac_plan_time_id ON t_tvac_plan (create_time, id);
CREATE INDEX IF NOT EXISTS idx_tvac_plan_article_time ON t_tvac_plan (article_id, create_time, id);
CREATE INDEX IF NOT EXISTS idx_tvac_plan_status_time ON t_tvac_plan (status, create_time, id);
CREATE INDEX IF NOT EXISTS idx_tvac_plan_start_time ON t_tvac_plan (plan_start_time);
CREATE INDEX IF NOT EXISTS idx_tvac_curve_article_cycle ON t_tvac_curve_point (article_id, cycle_no);
CREATE INDEX IF NOT EXISTS idx_tvac_frame_article_cycle ON t_tvac_tm_frame (article_id, cycle_no);
CREATE INDEX IF NOT EXISTS idx_tvac_frame_article_time ON t_tvac_tm_frame (article_id, frame_time);
CREATE INDEX IF NOT EXISTS idx_tvac_frame_limit ON t_tvac_tm_frame (limit_flag, article_id);

-- 遥测帧增加来源地面站设备编号（既有文件库平滑升级）
ALTER TABLE t_tvac_tm_frame ADD COLUMN IF NOT EXISTS source_device VARCHAR(64);

-- ============ tvac-3：观测数据 CSV 批量导入 ============

-- 导入批次：文件级 SHA-256 校验和唯一，重传同一文件直接返回原批次（文件幂等）
CREATE TABLE IF NOT EXISTS t_tvac_import_batch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_no VARCHAR(64) NOT NULL,
    file_name VARCHAR(255),
    file_checksum VARCHAR(64) NOT NULL,
    total_rows INT NOT NULL DEFAULT 0,
    success_count INT NOT NULL DEFAULT 0,
    updated_count INT NOT NULL DEFAULT 0,
    failed_count INT NOT NULL DEFAULT 0,
    shard_size INT NOT NULL DEFAULT 5000,
    shard_count INT NOT NULL DEFAULT 0,
    -- PROCESSING：仍有分片在处理；COMPLETED：全部分片处理完毕（允许存在逐行失败）
    status VARCHAR(16) NOT NULL DEFAULT 'PROCESSING',
    error_message VARCHAR(1000),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_import_checksum UNIQUE (file_checksum),
    CONSTRAINT uk_tvac_import_batch_no UNIQUE (batch_no)
);

-- 导入分片：按固定行数切分，独立事务、独立校验和；FAILED 分片可用原报文重试验跑
CREATE TABLE IF NOT EXISTS t_tvac_import_shard (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    shard_no INT NOT NULL,
    line_start INT NOT NULL,
    line_end INT NOT NULL,
    row_count INT NOT NULL DEFAULT 0,
    success_count INT NOT NULL DEFAULT 0,
    updated_count INT NOT NULL DEFAULT 0,
    failed_count INT NOT NULL DEFAULT 0,
    -- 本分片原文的 CRC32 校验和（hex），重试时复算比对，防止重试串片
    shard_checksum VARCHAR(16) NOT NULL,
    -- 分片原始报文，失败分片重试时重新解析（业务键幂等保证重试不重复落库）
    shard_payload CLOB,
    -- PENDING/PROCESSING/SUCCESS/FAILED
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    attempts INT NOT NULL DEFAULT 0,
    error_message VARCHAR(1000),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_import_shard UNIQUE (batch_id, shard_no),
    CONSTRAINT fk_tvac_import_shard_batch FOREIGN KEY (batch_id) REFERENCES t_tvac_import_batch(id)
);

-- 逐行结果：成功/更新/失败全部留痕，失败行同时写错误明细表
CREATE TABLE IF NOT EXISTS t_tvac_import_row (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    shard_no INT NOT NULL,
    line_no INT NOT NULL,
    record_type VARCHAR(16),
    biz_key VARCHAR(256),
    object_code VARCHAR(64),
    -- SUCCESS：新增；UPDATED：命中业务键且未锁定，执行覆盖；FAILED：校验/锁定失败
    result VARCHAR(16) NOT NULL,
    target_table VARCHAR(32),
    target_id BIGINT,
    create_time TIMESTAMP,
    CONSTRAINT fk_tvac_import_row_batch FOREIGN KEY (batch_id) REFERENCES t_tvac_import_batch(id)
);
CREATE INDEX IF NOT EXISTS idx_tvac_import_row_batch ON t_tvac_import_row (batch_id, line_no);

-- 错误明细：保留原始行号、字段、原值与失败原因，供地面站整改后重发
CREATE TABLE IF NOT EXISTS t_tvac_import_error (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT NOT NULL,
    shard_no INT NOT NULL,
    line_no INT NOT NULL,
    record_type VARCHAR(16),
    biz_key VARCHAR(256),
    field_name VARCHAR(64) NOT NULL,
    raw_value VARCHAR(1000),
    reason VARCHAR(512) NOT NULL,
    create_time TIMESTAMP,
    CONSTRAINT fk_tvac_import_error_batch FOREIGN KEY (batch_id) REFERENCES t_tvac_import_batch(id)
);
CREATE INDEX IF NOT EXISTS idx_tvac_import_error_batch ON t_tvac_import_error (batch_id, line_no);

-- 归一化观测数据台账：record_type + 业务键唯一，是文件校验和之外的第二道幂等防线
CREATE TABLE IF NOT EXISTS t_tvac_observation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id BIGINT,
    record_type VARCHAR(16) NOT NULL,
    biz_key VARCHAR(256) NOT NULL,
    article_id BIGINT,
    plan_id BIGINT,
    channel_id BIGINT,
    -- 投影到的业务表行（曲线点/遥测帧/判读报告）
    target_table VARCHAR(32),
    target_id BIGINT,
    object_code VARCHAR(64),
    plan_code VARCHAR(64),
    channel_code VARCHAR(64),
    observe_time TIMESTAMP,
    cycle_no INT,
    offset_sec INT,
    temperature_c DECIMAL(10,2),
    pressure_pa DECIMAL(18,4),
    frame_seq VARCHAR(64),
    raw_value VARCHAR(256),
    eng_value DECIMAL(16,4),
    limit_flag VARCHAR(8),
    conclusion VARCHAR(16),
    source_device VARCHAR(64),
    -- IMPORTED / UPDATED / REJECTED
    status VARCHAR(16) NOT NULL DEFAULT 'IMPORTED',
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_observation_biz UNIQUE (record_type, biz_key)
);
CREATE INDEX IF NOT EXISTS idx_tvac_observation_article ON t_tvac_observation (article_id, observe_time);

-- ============ tvac-3：地面站二进制解码结果分片重组 ============

-- 帧重组会话：一个带帧号的逻辑帧由多个通道分片构成，分片允许乱序到达、重复重发
CREATE TABLE IF NOT EXISTS t_tvac_frame_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_key VARCHAR(96) NOT NULL,
    frame_no VARCHAR(64) NOT NULL,
    article_id BIGINT NOT NULL,
    plan_id BIGINT NOT NULL,
    expected_pieces INT,
    good_pieces INT NOT NULL DEFAULT 0,
    bad_pieces INT NOT NULL DEFAULT 0,
    source_device VARCHAR(64),
    -- ASSEMBLING：收片中；ASSEMBLED：触发重组，按通道产出遥测帧，坏通道隔离留痕
    status VARCHAR(16) NOT NULL DEFAULT 'ASSEMBLING',
    assembled_time TIMESTAMP,
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_frame_session_key UNIQUE (session_key),
    CONSTRAINT fk_tvac_frame_session_article FOREIGN KEY (article_id) REFERENCES t_tvac_article(id),
    CONSTRAINT fk_tvac_frame_session_plan FOREIGN KEY (plan_id) REFERENCES t_tvac_plan(id)
);

-- 帧分片：某通道在某片序号上的二进制解码结果，到片即复算 CRC32 分片校验和
CREATE TABLE IF NOT EXISTS t_tvac_frame_piece (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    piece_seq INT NOT NULL,
    receive_seq INT NOT NULL,
    payload CLOB,
    raw_value VARCHAR(256),
    eng_value DECIMAL(16,4),
    cycle_no INT,
    frame_time TIMESTAMP,
    client_checksum VARCHAR(16),
    server_checksum VARCHAR(16),
    -- VERIFIED：校验通过；BAD：校验和不符（单通道坏帧，隔离不影响其他通道）；
    -- DUPLICATED：重复片（地面站重发），校验一致直接幂等丢弃
    status VARCHAR(16) NOT NULL DEFAULT 'VERIFIED',
    bad_reason VARCHAR(256),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_frame_piece UNIQUE (session_id, channel_id, piece_seq),
    CONSTRAINT fk_tvac_frame_piece_session FOREIGN KEY (session_id) REFERENCES t_tvac_frame_session(id),
    CONSTRAINT fk_tvac_frame_piece_channel FOREIGN KEY (channel_id) REFERENCES t_tvac_channel(id)
);
CREATE INDEX IF NOT EXISTS idx_tvac_frame_piece_session ON t_tvac_frame_piece (session_id, status);

-- ============ tvac-4：时序判读规则版本化与业务区间计算 ============

-- 时序判读规则集：挂在对象（试验件）上，mission_tz 为任务时区（观测以设备 UTC 为源，按此时区归区间）
CREATE TABLE IF NOT EXISTS t_tvac_rule_set (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_code VARCHAR(64) NOT NULL,
    set_name VARCHAR(128) NOT NULL,
    article_id BIGINT NOT NULL,
    -- 任务时区（IANA 时区ID，如 Asia/Shanghai），建档后不可改
    mission_tz VARCHAR(64) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'ENABLED',
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_rule_set_code UNIQUE (set_code),
    CONSTRAINT fk_tvac_rule_set_article FOREIGN KEY (article_id) REFERENCES t_tvac_article(id)
);
CREATE INDEX IF NOT EXISTS idx_tvac_rule_set_article ON t_tvac_rule_set (article_id);

-- 规则版本：同一规则集内版本号递增；DRAFT 可改区间，启用后不能原地修改，换版只能新建版本
CREATE TABLE IF NOT EXISTS t_tvac_rule_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    set_id BIGINT NOT NULL,
    version_no INT NOT NULL,
    -- DRAFT：草稿可改；ENABLED：启用（同集仅一个启用版，启用新版自动停用旧版）；DISABLED：已停用
    status VARCHAR(16) NOT NULL DEFAULT 'DRAFT',
    enabled_time TIMESTAMP,
    remark VARCHAR(512),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_rule_version UNIQUE (set_id, version_no),
    CONSTRAINT fk_tvac_rule_version_set FOREIGN KEY (set_id) REFERENCES t_tvac_rule_set(id)
);

-- 规则区间（业务区间）：任务时区当日分钟 [start_min, end_min) 左闭右开；
-- end_min <= start_min 表示跨日（如 22:00-次日10:00）；同版本内区间重叠必须拒绝
CREATE TABLE IF NOT EXISTS t_tvac_rule_band (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version_id BIGINT NOT NULL,
    -- PEAK 峰值 / FLAT 平段 / VALLEY 谷值
    band_type VARCHAR(16) NOT NULL,
    start_min INT NOT NULL,
    end_min INT NOT NULL,
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT fk_tvac_rule_band_version FOREIGN KEY (version_id) REFERENCES t_tvac_rule_version(id)
);
CREATE INDEX IF NOT EXISTS idx_tvac_rule_band_version ON t_tvac_rule_band (version_id);

-- 区间计算批次：同一（规则版本 + UTC 窗口）唯一，重算幂等返回原批次；
-- 并发重算由 uk_tvac_calc_run_scope 兜底，不会产生两份结果
CREATE TABLE IF NOT EXISTS t_tvac_calc_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_no VARCHAR(64) NOT NULL,
    set_id BIGINT NOT NULL,
    version_id BIGINT NOT NULL,
    version_no INT NOT NULL,
    article_id BIGINT NOT NULL,
    -- 计算窗口（设备 UTC，左闭右开）
    window_start_utc TIMESTAMP NOT NULL,
    window_end_utc TIMESTAMP NOT NULL,
    mission_tz VARCHAR(64) NOT NULL,
    -- 计算采用的规则区间快照（JSON），历史结果读取以快照为准，换版不污染
    snapshot_json CLOB NOT NULL,
    obs_count INT NOT NULL DEFAULT 0,
    status VARCHAR(16) NOT NULL DEFAULT 'DONE',
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT uk_tvac_calc_run_no UNIQUE (run_no),
    CONSTRAINT uk_tvac_calc_run_scope UNIQUE (version_id, window_start_utc, window_end_utc),
    CONSTRAINT fk_tvac_calc_run_set FOREIGN KEY (set_id) REFERENCES t_tvac_rule_set(id),
    CONSTRAINT fk_tvac_calc_run_version FOREIGN KEY (version_id) REFERENCES t_tvac_rule_version(id),
    CONSTRAINT fk_tvac_calc_run_article FOREIGN KEY (article_id) REFERENCES t_tvac_article(id)
);
CREATE INDEX IF NOT EXISTS idx_tvac_calc_run_set ON t_tvac_calc_run (set_id, id);
CREATE INDEX IF NOT EXISTS idx_tvac_calc_run_article ON t_tvac_calc_run (article_id, id);

-- 计算明细：每区间一行；累计值 BigDecimal 全精度累加，均值仅在最终步骤统一舍入
CREATE TABLE IF NOT EXISTS t_tvac_calc_detail (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    band_id BIGINT NOT NULL,
    band_type VARCHAR(16) NOT NULL,
    start_min INT NOT NULL,
    end_min INT NOT NULL,
    obs_count INT NOT NULL DEFAULT 0,
    sum_value DECIMAL(28,4),
    min_value DECIMAL(16,4),
    max_value DECIMAL(16,4),
    avg_value DECIMAL(28,4),
    create_by BIGINT,
    create_time TIMESTAMP,
    update_by BIGINT,
    update_time TIMESTAMP,
    CONSTRAINT fk_tvac_calc_detail_run FOREIGN KEY (run_id) REFERENCES t_tvac_calc_run(id)
);
CREATE INDEX IF NOT EXISTS idx_tvac_calc_detail_run ON t_tvac_calc_detail (run_id);

-- 判读报告关联计算批次/规则版本（既有文件库平滑升级）；验收/落账后绑定锁定
ALTER TABLE t_tvac_report ADD COLUMN IF NOT EXISTS calc_run_id BIGINT;
ALTER TABLE t_tvac_report ADD COLUMN IF NOT EXISTS rule_version_id BIGINT;
